apiVersion: apps/v1
kind: Deployment
metadata: 
  name: jy-msa-ordering-depl
  namespace: jykim-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jy-msa-ordering
  template:
    metadata:
      labels:
        app: jy-msa-ordering
    spec:
      containers:
      - name: jy-order-backend
        image: 346903264902.dkr.ecr.ap-northeast-2.amazonaws.com/jy-msa-order:latest
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: jy-app-secrets
              key: DB_HOST
        - name: DB_PW
          valueFrom:
            secretKeyRef:
              name: jy-app-secrets
              key: DB_PW
        - name: AWS_KEY
          valueFrom:
            secretKeyRef:
              name: jy-app-secrets
              key: AWS_KEY
        - name: AWS_SECRET
          valueFrom:
            secretKeyRef:
              name: jy-app-secrets
              key: AWS_SECRET

---
apiVersion: v1
kind: Service
metadata:
  name: jy-msa-ordering-service
  namespace: jykim-ns
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: jy-msa-ordering

    