apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jy-order-backend-service
  namespace: jykim-ns
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1 #첫번쨰 prefix제거
    cert-magager.io/cluster-issuer: my-issuer
spec:
  tls:
  - hosts:
     - "server.jy1187.shop"
    secretName: server-jy1187-com-tls
  rules:
  - host: server.jy1187.shop  # 설정하려는 도메인 이름. 제외시에 elb(로드밸런서) 주소로도 접근할수 있는 모든 도메인 접근 가능.
    http:
      paths:
      - path: /(.*) #모든 url요청을 nginx-service로 라우팅
        pathType: Prefix
        backend:
          service:
            name: jy-order-backend-service
            port:
              number: 80

---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: my-issuer
  namespace: jykim-ns
spec:
  acme:
  # 인증서 서버 주소. 해당 서버의 리소스를 통해 인증서 발행
    server: https://acme-v02.api.letsencrypt.org/directory
  # 인증서 만료 또는 갱신 필요시 알람 email
    email: rifkehtm862@gmail.com
    privateKeySecretRef:
      name: my-issuer
    solvers:
    - http01:
        ingress:
          class: nginx
---
# 3.ClusterIssue를 사용하여 Certificate 리소스 생성 : Certificate리소스 생성시에 인증서 발급
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: server-jy1187-com-tls
  namespace: jykim-ns
spec:
  secretName: server-jy1187-com-tls
  duration: 2160h #90day
  renewBefore: 360h #before 15day
  issuerRef:
    name: my-issuer
    kind: ClusterIssuer
  commonName: server.jy1187.shop
  dnsNames:
  - server.jy1187.shop